server:
  host: "0.0.0.0"
  port: "8080"
datasource:
  url: postgres://user:password@localhost:5432/nimbus-notify?sslmode=disable
weather-provider:
  url: https://api.weatherapi.com/v1
  key: key
email-service:
  domain: ""
  key: key
  sender: postmaster@sandboxfd255faff9e0446a99721a7eb078fbb4.mailgun.org
emails:
  - name: "confirmation"
    subject: "Confirm subscription"
    text: "To confirm your subscription use http://db35m6zjaamdj.cloudfront.net/api/confirm/%s"
  - name: "confirmation-successful"
    subject: "Confirmation successful"
    text: "You have successfully subscribed for weather update. To unsubscribe use http://db35m6zjaamdj.cloudfront.net/api/unsubscribe/%s"
  - name: "weather"
    subject: "Weather Update"
    text: "Weather for %s: Temp: %f Hum: %f Desc: %s To unsubscribe use http://db35m6zjaamdj.cloudfront.net/api/unsubscribe/%s"
  - name: "unsubscribe"
    subject: "End of subscription"
    text: "You have successfully unsubscribed"
